package ch.heigvd.iict.entities

import ch.heigvd.iict.services.protocol.MessageType
import ch.heigvd.iict.services.protocol.OperationType
import io.hypersistence.utils.hibernate.type.json.JsonType
import io.quarkus.hibernate.orm.panache.kotlin.PanacheEntityBase
import jakarta.persistence.*
import org.hibernate.annotations.Type
import java.time.Instant

/**
 * Logs a message initiated by a beacon and relayed to the server.
 *
 * This is used for the beacon-to-server communication flow, such as when a beacon
 * sends a status update in response to a server command.
 */
@Entity
@Table(name = "inbound_messages")
@SequenceGenerator(name = "inbound_messages_seq", sequenceName = "inbound_messages_seq", allocationSize = 50)
class InboundMessage : PanacheEntityBase {

    /** The primary key for this message record. */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "inbound_messages_seq")
    var id: Long? = null

    /** A reference to the [Beacon] that originated this message. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "beacon_id", nullable = false)
    lateinit var beacon: Beacon

    /** The message ID generated by the beacon, used for idempotency. */
    @Column(nullable = false)
    var beaconMsgId: Long = 0L

    /** The type of the message (e.g., REQ, ACK, ERR). */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    lateinit var msgType: MessageType

    /** The specific operation this message relates to (e.g., RESPONSE_BEACON_STATUS). */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    lateinit var opType: OperationType

    /** The beacon's monotonic counter value at the time the message was created. */
    @Column(nullable = false)
    var beaconCounter: Long = 0L

    /** The JSON payload of the message, if any (e.g., a beacon status report). */
    @Type(JsonType::class)
    @Column(columnDefinition = "jsonb")
    var payload: String? = null // The status JSON from the beacon

    /** The timestamp when the server received this message. */
    @Column(nullable = false, updatable = false)
    lateinit var receivedAt: Instant

    /** Sets the [receivedAt] timestamp on initial persistence. */
    @PrePersist
    fun onPrePersist() {
        receivedAt = Instant.now()
    }
}