package ch.heigvd.iict.entities

import ch.heigvd.iict.services.protocol.MessageStatus
import ch.heigvd.iict.services.protocol.OperationType
import jakarta.persistence.*
import java.time.Instant
import io.hypersistence.utils.hibernate.type.json.JsonType
import io.quarkus.hibernate.orm.panache.kotlin.PanacheEntityBase
import org.hibernate.annotations.Type

/**
 * Represents an outbound message job from the server to a beacon.
 *
 * This acts as the central record for a command or task that needs to be delivered
 * to a beacon via the opportunistic data mule system.
 */
@Entity
@Table(name = "outbound_messages")
@SequenceGenerator(
    name = "outbound_messages_seq",
    sequenceName = "outbound_messages_seq",
    allocationSize = 50
)
class OutboundMessage : PanacheEntityBase {

    /** The primary key for this outbound message job. */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "outbound_messages_seq")
    var id: Long? = null

    /** The target [Beacon] for this message. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "beacon_id", nullable = false)
    lateinit var beacon: Beacon

    /** The current lifecycle status of this message job. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    lateinit var status: MessageStatus

    /** The original, unencrypted command payload as a JSON string. */
    @Type(JsonType::class)
    @Column(columnDefinition = "jsonb", nullable = false)
    lateinit var commandPayload: String // Store JSON as a string

    /** The final, encrypted data blob that is sent to phones for delivery. */
    @Column(columnDefinition = "bytea")
    var encryptedBlob: ByteArray? = null

    /** A unique identifier for this message, generated by the server. */
    @Column(nullable = false, unique = true)
    var serverMsgId: Long = 0L

    /** The desired number of phones that should attempt to deliver this message. */
    @Column(nullable = false)
    var redundancyFactor: Int = 1

    /** The current count of phones that have fetched this message job for delivery. */
    @Column(nullable = false)
    var deliveryCount: Int = 0

    /** The specific operation type of the command within the payload. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    lateinit var opType: OperationType

    /** The timestamp when this message job was created. */
    @Column(nullable = false, updatable = false)
    lateinit var createdAt: Instant

    /** The timestamp when the first successful acknowledgment was received for this job. */
    var firstAcknowledgedAt: Instant? = null

    /** A list of all [MessageDelivery] attempts for this message job. */
    @OneToMany(mappedBy = "outboundMessage", cascade = [CascadeType.ALL], orphanRemoval = true, fetch = FetchType.LAZY)
    lateinit var deliveries: MutableList<MessageDelivery>

    /** Sets the [createdAt] timestamp on initial persistence. */
    @PrePersist
    fun onPrePersist() {
        createdAt = Instant.now()
    }
}