package ch.heig.iict.polaris_health.domain.repository

import ch.drcookie.polaris_sdk.api.SdkError
import ch.drcookie.polaris_sdk.api.SdkResult
import ch.drcookie.polaris_sdk.protocol.model.PoLToken

interface TokenRepository {

    /**
     * Stores a PoLToken generated by the SDK in the local DB.
     * @param patientId The patient id for which the token has been generated.
     * @param token The token received from the SDK.
     */
    suspend fun storeToken(patientId: Long, token: PoLToken)

    /**
     * Tries to synchronize all non-sync tokens with the server.
     * @return A SdkResult showing success or failure of the operation.
     */
    suspend fun syncPendingTokens(): SdkResult<Int, SdkError>
}